Repository Shubhamlmp/Programming-Practice, pull requests merged in 2022-10, with the labels that each got.

#51 Added Solutions to Problem 27 - 32 + Readme Link Updation
  C++/27_The_last_2_digits.cpp
  C++/28_1_to_N.cpp
  C++/29_Even_Numbers.cpp
  C++/30_Even,Odd,Positive_and_Negative.cpp
  C++/31_Fixed_Password.cpp
  C++/32_max.cpp
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#53 Corrected table format in README.md
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#63 fixed issue #56 -solution for 43,44,45,46 added
  C++/43_Shape1.cpp
  C++/44_Digits.cpp
  C++/45_SequenceOfNumber_Sum.cpp
  C++/46_SumOf_consecutiveOdd_no.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#59 issue #57
  C++/Shape2.cpp
  C++/Shape3.cpp
  C++/USomeSums.cpp
  C++/VPUM.cpp
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#113 Added new Linked List questions
  C++/Append_LL.cpp
  C++/Delete_Node_LL.cpp
  C++/EliminateDuplicates_LL.cpp
  C++/Find_a_node_LL.cpp
  C++/Insert_recursive_LL.cpp
  C++/Length_of_LL_LL.cpp
  C++/Length_recursive_LL.cpp
  C++/Print_ith_node_LL.cpp
  C++/reverse_LL.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#118 added #96
  C++/freq.cpp
  C++/mirror.cpp
  C++/neighbours.cpp
  C++/rangeSumQuery.cpp
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#247 Glitch Effect Project Using HTML,CSS
  Projects/Glitch_Effect/index.html
  Projects/Glitch_Effect/styles.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#250 patch for page loader project
  Projects/Page_Loader/index.html
  Projects/Page_Loader/styles.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#251 implemented typing speed test in python
  Projects/TestTypingSpeed/testTypingSpeed.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, easy

#252 implemented youtube downloader using python
  Projects/YoutubeVideoDownloader/main.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#262 Added beginner level python project
  Beginner_project_number _guess.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#270 Added some OOPS question in java
  classes and objects ques/q1.java
  classes and objects ques/q2.java
  classes and objects ques/q3.java
Labels: hacktoberfest, hacktoberfest-accepted

#272 Heap sort in c++
  Heap.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#287 Added stone paper scissors game in python
  Projects/Stone-Paper-Scissor/stone-paper-scissor.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#286 Added the solution for Expressions(Palindome Replace)
  C++/Expression_PalindromeReplace.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#285 added c project
  voting-system/election.h
  voting-system/main.c
  voting-system/projectinformation.txt
Labels: hacktoberfest, hacktoberfest-accepted

#283 added folder for C# to find factorial of a number
  C#/findFactorial.cs
Labels: hacktoberfest, hacktoberfest-accepted

#280 Basics of Array filter function
  JavaScript/arrayFilters.js
Labels: hacktoberfest, hacktoberfest-accepted

#282 added javascript project
  Basic_JavaScript_Project/Weather App/README.md
  Basic_JavaScript_Project/Weather App/index.html
  Basic_JavaScript_Project/Weather App/script.js
  Basic_JavaScript_Project/Weather App/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#290 Add
  C/Add
Labels: hacktoberfest, hacktoberfest-accepted

#291 Inverted Pyramid
  C/Inverted Pyramid
Labels: hacktoberfest, hacktoberfest-accepted

#293 issue #279 added 11_iLoveStrings.cpp
  C++/11_iLoveStrings.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#292 Swap
  C/Swap
Labels: hacktoberfest, hacktoberfest-accepted

#300 Add. MP4 to GIF converter using OpenCV (#274)
  Projects/MP4_to_GIF_Converter/README.md
  Projects/MP4_to_GIF_Converter/bird.mp4
  Projects/MP4_to_GIF_Converter/main.py
  Projects/MP4_to_GIF_Converter/requirements.txt
Labels: hacktoberfest, hacktoberfest-accepted

#299 Add One Row To Tree Leetcode
  Add One Row To Tree
Labels: hacktoberfest, hacktoberfest-accepted

#298 Invert Pyramid made from Asterisk (*)
  C++/InvertPyramid.c++
Labels: hacktoberfest, hacktoberfest-accepted

#296 Added the solution for Watermelon
  C++/Watermelon.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#295 project added
  Projects/Quote of the day/index.html
  Projects/Quote of the day/output.png
  Projects/Quote of the day/quotes.css
  Projects/Quote of the day/quotes.js
Labels: hacktoberfest, hacktoberfest-accepted

#294 Patterns in C++
  Pattern/Pascal's Triangle.cpp
  Pattern/Pyramid.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#301 Added count_subarrays.cpp, add.cpp, n_times.cpp, power_of_two.cpp
  C++/InvertPyramid.c++
  C++/add.cpp
  C++/count_subarrays.cpp
  C++/n_times.cpp
  C++/power_of_two.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#302 Added xor.cpp
  C++/xor.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#303 Create Shift zero
  C/Shift zero
Labels: hacktoberfest, hacktoberfest-accepted

#304 Create Average
  C/Average
Labels: hacktoberfest, hacktoberfest-accepted

#305 create maths_1_add
  maths_1_add
Labels: hacktoberfest, hacktoberfest-accepted

#306 Add solution for Power of Two
  Python/power_of_two.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#307 Add solution for ADD
  Python/add.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#308 Add solution for Palindrome
  Python/palindrome.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#314 Addition of inputted nos:
  add_nos.java
Labels: hacktoberfest, hacktoberfest-accepted

#313 Get the GCC of NOS.
  GCC_nos.c
Labels: hacktoberfest, hacktoberfest-accepted

#312 Adding my C++ project BMI.cpp
  BMI.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#310 add satendragangwar information
  C++/C++ - Shortcut.lnk
  C++/code.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#309 Add solution for average
  Python/average.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#316 PRINT in python
  Python/PRINT.py
Labels: hacktoberfest, hacktoberfest-accepted

#317 Create diameter of a Binary Tree.cpp
  C++/diameter of a  Binary Tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#319 Create practice pandas.py
  Python/practice pandas.py
Labels: hacktoberfest, hacktoberfest-accepted

#320 Roman Numeral to Integer
  Python/Roman To Integer.py
Labels: hacktoberfest, hacktoberfest-accepted

#321 Create pandas.py
  Basic_Python_Project/pandas.py
Labels: hacktoberfest, hacktoberfest-accepted

#322 Create snake game.py
  Basic_Python_Project/snake game.py
Labels: hacktoberfest, hacktoberfest-accepted

#323 Create pong game.py
  Basic_Python_Project/pong game.py
Labels: hacktoberfest, hacktoberfest-accepted

#324 Palindrome in c
  C/Palindrome.c
Labels: hacktoberfest, hacktoberfest-accepted

#325 Create N times
  C/N times
Labels: hacktoberfest, hacktoberfest-accepted

#326 Create Print Even Indices
  C/Print Even Indices
Labels: hacktoberfest, hacktoberfest-accepted

#327 code for palindrome array in python
  Python/fibo.py
  Python/palindrome_array.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#328 Create trie.cpp
  C++/trie.cpp
Labels: good first issue, hacktoberfest

#330 Added Trees with CPP
  Contains x.cpp
  Count leaf nodes.cpp
  Count nodes.cpp
  Find height.cpp
  Find sum of nodes.cpp
  Max data node.cpp
  Next larger.cpp
  Node with maximum child sum.cpp
  PostOrder traversal.cpp
  Print level wise.cpp
  Replace with depth.cpp
  Second largest element in tree.cpp
  Structurally identical.cpp
Labels: hacktoberfest, hacktoberfest-accepted, easy

#331 Create Solution.java
  Solution.java
Labels: hacktoberfest, hacktoberfest-accepted

#332 Calc in c
  Calc.c
Labels: hacktoberfest, hacktoberfest-accepted

#333 Calc in c++
  Calc.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#336 Update README.md
  C++/swap.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#335 Odd and Even in java
  Odd_or_Even.java
Labels: hacktoberfest, hacktoberfest-accepted

#315 Added c++ loops.
  1.cpp
  1.exe
  do_while.cpp
  do_while.exe
  forloops.cpp
  forloops.exe
  switch_case.cpp
  switch_case.exe
  table.cpp
  table.exe
  while_loop.cpp
  while_loop.exe
Labels: hacktoberfest, hacktoberfest-accepted

#337 added new_array.cpp
  C++/new_array.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#338 added divisible.cpp
  C++/divisible.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#339 Added solution for I Love Strings.
  C++/I_Love_Strings.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#340 Added solution for Print
  C++/Print.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#341 added solution for distinct numbers (Maths) in c++
  C++/13.Distinctnumbers.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#342 Added sort strings(String) in C++
  C++/15.SortString.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#344 Create 15_sort_string.cpp
  C++/15_sort_string.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#343 Added Palindromes Replace (Hard) ,Replace from the left (Hard) in C++ Max number in C++
  C++/02.Replacefromthe left
  C++/1.PalindromesReplace.cpp
  C++/11.Maxnumber.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#345 Added Suffix sum in C++.
  C++/13.Suffix_sum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#349 Added code for Count Vowels
  Python/ageindays.py
  Python/coordinatesofpoint.py
  Python/countvowels.py
Labels: hacktoberfest, hacktoberfest-accepted

#350 Maximum pairwise product
  Python/max_pairwise_product_efficient.py
Labels: hacktoberfest, hacktoberfest-accepted

#353 Adding Y-shaped-pattern.cpp
  Pattern/Y-shaped-pattern.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#352 All Data structures in c++
  dsa-code/LinkedListH1.cpp
  dsa-code/Tries&Huffman_1.cpp
  dsa-code/binaryTree_1.cpp
  dsa-code/binaryTree_2.cpp
  dsa-code/binaryTree_3.cpp
  dsa-code/binaryTree_4.cpp
  dsa-code/binarysearchTree_1.cpp
  dsa-code/binarysearchTree_2.cpp
  dsa-code/binarysearchTree_3.cpp
  dsa-code/carRunner.cpp
  dsa-code/code1.cpp
  dsa-code/code1.exe
  dsa-code/code1.o
  dsa-code/demo.cpp
  dsa-code/graph_1.cpp
  dsa-code/graph_2.cpp
  dsa-code/graph_3.cpp
  dsa-code/graph_4.cpp
  dsa-code/hashmap_1.cpp
  dsa-code/hashmap_2.cpp
  dsa-code/hashmap_3.cpp
  dsa-code/hashmap_4.cpp
  dsa-code/header/binarySearchTree.h
  dsa-code/header/binaryTree.h
  dsa-code/header/car.h
  dsa-code/header/demoheader.h
  dsa-code/header/linkedList.h
  dsa-code/header/tree.h
  dsa-code/linked_list_1.cpp
  dsa-code/linked_list_2.cpp
  dsa-code/linked_list_3.cpp
  dsa-code/linked_list_4.cpp
  dsa-code/priorityQueue_1.cpp
  dsa-code/priorityQueue_2.cpp
  dsa-code/recursion1.cpp
  dsa-code/recursion2.cpp
  dsa-code/recursion2.exe
  dsa-code/recursion2.o
  dsa-code/recursion3.cpp
  dsa-code/recursion3.exe
  dsa-code/recursion3.o
  dsa-code/snippet.cpp
  dsa-code/stack_and_queue_1.cpp
  dsa-code/stack_and_queue_2.cpp
  dsa-code/stack_and_queue_3.cpp
  dsa-code/stack_and_queue_4.cpp
  dsa-code/stack_and_queue_5.cpp
  dsa-code/stack_and_queue_6.cpp
  dsa-code/treeH1.cpp
  dsa-code/tree_1.cpp
  dsa-code/tree_2.cpp
  dsa-code/vector_1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#351 Added code for Count Words
  Python/countwords.py
Labels: hacktoberfest, hacktoberfest-accepted

#354 Create add_two_linkedlist.py
  Python/Add_two_linkedlist.py
Labels: hacktoberfest, hacktoberfest-accepted

#355 Create lcs.cpp
  C++/lcs.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#356 Created LCM.py
  Python/LCM.py
Labels: hacktoberfest, hacktoberfest-accepted

#357 Created GCD.py
  Python/GCD.py
Labels: hacktoberfest, hacktoberfest-accepted

#358 Parentheses Combinations
  Python/Parentheses.py
Labels: hacktoberfest, hacktoberfest-accepted

#359 Uploaded matrixElementsSum.py file
  Python/matrixElementsSum.py
Labels: hacktoberfest, hacktoberfest-accepted

#363 added project under 100 lines of code in c
  Rock-Paper-Scissor/information.txt
  Rock-Paper-Scissor/main.c
Labels: hacktoberfest, hacktoberfest-accepted

#375 Add 05_Swap.cpp
  C++/05_Swap.cpp
  C++/13_Distinct_Numbers.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#378 Create Prime_checking.py
  Python/Prime_checking.py
Labels: hacktoberfest, hacktoberfest-accepted

#371 Create PersonInheritance.java
  PersonInheritance.java
Labels: hacktoberfest, hacktoberfest-accepted

#372 Create India.java
  India.java
Labels: hacktoberfest, hacktoberfest-accepted

#373 Create quickSort.cpp
  quickSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#376 Create prime function
  Python/prime function
Labels: hacktoberfest, hacktoberfest-accepted

#370 Create SmartPhones.java
  SmartPhones.java
Labels: hacktoberfest, hacktoberfest-accepted

#369 Create TryCatchDivision.java
  TryCatchDivision.java
Labels: hacktoberfest, hacktoberfest-accepted

#368 Create Whatsapp.java
  Whatsapp.java
Labels: hacktoberfest, hacktoberfest-accepted

#367 Create OverloadingOperator.java
  OverloadingOperator.java
Labels: hacktoberfest, hacktoberfest-accepted

#364 BubbleSort.cpp
  C++/BubbleSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#365 Create Swap
  Python/Swap
Labels: hacktoberfest, hacktoberfest-accepted

#366 Create PRINT
  Python/PRINT
Labels: hacktoberfest, hacktoberfest-accepted
